from shiny import ui

INPUTS = {
    "id": ui.input_text("id", "Enter your first name"),
    "lname": ui.input_text("lname", "Enter your last name"),
    "dob": ui.input_date("dob", "Date of birth"),
    "forgetToTake": ui.input_radio_buttons(
        "forgetToTake",
        "I just forget to take my medicines some of the time.",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

     "runOut": ui.input_radio_buttons(
        "runOut",
        "I run out of my medicine because I don’t get refills on time.",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),
     
      "inconvenient": ui.input_radio_buttons(
        "inconvenient",
        "Taking medicines more than once a day is inconvenient.",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

      "feelConfident": ui.input_radio_buttons(
        "feelConfident",
        "I feel confident that each one of my medicines will help me.",
        { 1: "Strongly agree",
          2: "Agree", 
          3: "Neutral",
          4: "Disagree",
          5: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

      "knowGoals": ui.input_radio_buttons(
        "knowGoals",
        "I know if I am reaching my health goals.",
        { 1: "Strongly agree",
          2: "Agree", 
          3: "Neutral",
          4: "Disagree",
          5: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "haveSomeone": ui.input_radio_buttons(
        "haveSomeone",
        "I have someone I can call with questions about my medicines.",
        { 1: "Strongly agree",
          2: "Agree", 
          3: "Neutral",
          4: "Disagree",
          5: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "workTogether": ui.input_radio_buttons(
        "workTogether",
        "My doctor/nurse and I work together to make decisions.",
        { 1: "Strongly agree",
          2: "Agree", 
          3: "Neutral",
          4: "Disagree",
          5: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "takenMedicineMoreOften": ui.input_radio_buttons(
        "takenMedicineMoreOften",
        "Taken a medicine more or less often than prescribed?",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "skippedMedicine": ui.input_radio_buttons(
        "skippedMedicine",
        "Skipped or stopped taking a medicine because you didn’t think it was working?",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "skippedMedicineBecauseOfSideEffects": ui.input_radio_buttons(
        "skippedMedicineBecauseOfSideEffects",
        "Skipped or stopped taking a medicine because it made you feel bad?",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "skippedMedicineBecauseOfCost": ui.input_radio_buttons(
        "skippedMedicineBecauseOfCost",
        "Skipped, stopped, not refilled, or taken less medicine because of the cost?",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),

    "notHadMedicineWithYou": ui.input_radio_buttons(
        "notHadMedicineWithYou",
        "Not had medicine with you when it was time to take it?",
        { 5: "Strongly agree",
          4: "Agree", 
          3: "Neutral",
          2: "Disagree",
          1: "Strongly disagree"},
        selected=[],
        inline=True,
    ),
}
